name: "CI & CD"

on: [push]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}


jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1      
      - name: Build and deploy the Docker image      
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          heroku container:push -a dantunkurashowroomapi web  
          heroku container:release -a dantunkurashowroomapi web
