name: "CI & CD"

on: [push]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}


jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Install curl module
        shell: powershell
        run: choco install curl --no-progress

      - name: Testing WSL
        shell: powershell
        run: wsl      
