name: "CI & CD"

on: [push]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}


jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Install Heroku CLI PowerShell Module
        shell: powershell
        run: |
          choco install heroku-cli --version=7.0.100.0
          refreshenv

      - uses: actions/checkout@v1      
      - name: Login to Heroku
        shell: powershell
        run: heroku container:login  

      - name: Build and Push
        shell: powershell
        run: heroku container:push -a dantunkurashowroomapi web
      - name: Deploy
        shell: powershell
        run: heroku container:release -a dantunkurashowroomapi web
