name: "CI & CD"

on: [push]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}


jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Install 7Zip PowerShell Module
        shell: powershell
        run: |
          Install-Module Choco -Force -Verbose
          Install-Choco 
          choco install heroku-cli --version=7.0.100.0 --force -y
          refreshenv

      - uses: actions/checkout@v1      
      - name: Login to Heroku
        run: heroku container:login  

      - name: Build and Push
        run: heroku container:push -a dantunkurashowroomapi web
      - name: Deploy
        run: heroku container:release -a dantunkurashowroomapi web